
export const SELECT_REDDIT = 'SELECT_REDDIT';
export const SET_APP_STORE_FILTER = 'SET_APP_STORE_FILTER';
export const SET_GLUE_STORE_FILTER = 'SET_GLUE_STORE_FILTER';
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FETCH_PROTECTED_DATA_REQUEST = 'FETCH_PROTECTED_DATA_REQUEST';
export const RECEIVE_PROTECTED_DATA = 'RECEIVE_PROTECTED_DATA';
